using IntelligentPersonalHealthOptimization.Data;
using IntelligentPersonalHealthOptimization.Services.Interfaces;

namespace IntelligentPersonalHealthOptimization.Services.Implementation;

/// <summary>
/// Loads exercise demonstration images bundled as MauiAssets under
/// Resources/Raw/exercise_demos/. The name→filename map is auto-generated by
/// Tools/fetch_exercise_demos.py.
/// </summary>
public class BundledExerciseMediaService : IBundledExerciseMediaService
{
    public string Attribution => "via Free Exercise DB (MIT)";

    public ImageSource? TryGetImage(string exerciseName)
    {
        if (string.IsNullOrWhiteSpace(exerciseName)) return null;
        if (!ExerciseMediaMap.NameToImageFile.TryGetValue(exerciseName, out var filename))
            return null;

        // MauiAssets are accessed by their LogicalName via FileSystem.OpenAppPackageFileAsync.
        // The csproj sets LogicalName = "%(RecursiveDir)%(Filename)%(Extension)" so the
        // file is reachable at "exercise_demos/<filename>".
        var assetPath = $"exercise_demos/{filename}";
        return ImageSource.FromStream(async ct => await FileSystem.OpenAppPackageFileAsync(assetPath));
    }
}
